### ISSUE TITLE
onchip_flash_0 Required

### ISSUE THREAD

**Issue by Conlin6241** [dimag0g/nios_duino#10]
I am unable to generate the HDL because the SOPC builder (qsys Platform Designer) says the onchip_flash_0 IP needs to be connected to the NIOS II instruction_master. However, I am using the Cyclone V GX Starter Kit FPGA, which does not support the on-chip flash module. I do have an EPCQ flash chip on board, however, and was hoping to use the EPCQ controller instead, is this possible?

<img width="958" alt="nios_duino_qsys" src="https://user-images.githubusercontent.com/84931710/119883440-674f4000-bee4-11eb-8688-63f5eef4d68f.png">

**Comment by dimag0g** [comment]
Yes, it should be possible. I remember using an EPCS controller with an old Cyclone IV, and AFAIK EPCQ is just a faster interface with similar functions.

**Comment by Conlin6241** [comment]
Ok, the onchip_flash IP was the default reset vector memory for the Nios II, what would you recommend I use as the reset vector memory instead?

**Comment by Conlin6241** [comment]
I was able to fix this issue by following the example from Issue #1
