### ISSUE TITLE
'Undefined Reference' Errors

### ISSUE THREAD

**Issue by Conlin6241** [dimag0g/nios_duino#11]
Hello,

I am currently trying to build the Nios II Application for the project I am working on, but I have come across these errors in the process:

    C:\Users\seanc\Desktop\Sawblade_Project\Quartus\RTL_Freeze_V1.0\nios_duino-master\nios_duino-master\software\nios_duino/arduino/EEPROM.h:42: undefined reference to `eeprom_read_byte'

    C:\Users\seanc\Desktop\Sawblade_Project\Quartus\RTL_Freeze_V1.0\nios_duino-master\nios_duino-master\software\nios_duino/arduino/EEPROM.h:47: undefined reference to `eeprom_write_byte'

    C:\Users\seanc\Desktop\Sawblade_Project\Quartus\RTL_Freeze_V1.0\nios_duino-master\nios_duino-master\software\nios_duino/Test.cpp:42: undefined reference to `analogRead'

    C:\Users\seanc\Desktop\Sawblade_Project\Quartus\RTL_Freeze_V1.0\nios_duino-master\nios_duino-master\software\nios_duino/arduino/EEPROM.h:42: undefined reference to `eeprom_read_byte'

In addition, I am also receiving this warning:

    C:\Users\seanc\Desktop\Sawblade_Project\Quartus\RTL_Freeze_V1.0\nios_duino-master\nios_duino-master\software\nios_duino/arduino/HardwareSerial.cpp:49: warning: warning: open is not implemented and will always fail

For my project I am Using a Cyclone V GX dev board and will be executing the code in place from the EPCQ flash, so I used the "Hello World Small" as my template. I have included the nios_duino library in the Application as shown below.

<img width="959" alt="NIOS-II-application" src="https://user-images.githubusercontent.com/84931710/125853966-34f22404-df7e-4a3e-a810-f2ef6bc90bc9.png">

Any assistance would be greatly appreciated!

**Comment by dimag0g** [comment]
`eeprom_read_byte` should be defined in `avr/eeprom.h` inside the `arduino` folder. Check that this file didn't get accidentally overwritten, and that there isn't a different version of this file in your include path.

Renaming/removing an include file and recompiling is a simple way to make sure you're looking at the file that really is included. 

I have a feeling that solving this one issue might solve the others as well.

**Comment by Conlin6241** [comment]
So after double checking through my include path, the only '<eeprom.h>' file present is in '<arduino/avr>. I don't believe it has been overwritten, but just in case, I have included both the code for the file, as well as screenshots of my include path.

    //! NIOSDuino custom file, (c) Dmitry Grigoryev, 2018

    #ifndef _AVR_EEPROM_H_
    #define _AVR_EEPROM_H_

    #include <inttypes.h>

    #ifdef __cplusplus
    extern "C" {
    #endif

    #define E2END 1023

    uint8_t eeprom_read_byte (const uint8_t *p);
    void eeprom_write_byte (uint8_t *p, uint8_t value);

    #ifdef __cplusplus
    }
    #endif

    #endif

<img width="228" alt="Include_path1" src="https://user-images.githubusercontent.com/84931710/125872134-f190eee2-9159-4830-aae6-f4079e6a4def.png">
<img width="281" alt="Include_path2" src="https://user-images.githubusercontent.com/84931710/125872141-0cb158a5-38ac-4698-9d8d-1762f41489d0.png">
<img width="283" alt="Include_path3" src="https://user-images.githubusercontent.com/84931710/125872145-74f2b01a-4179-4352-86c4-768b7dfa9a4a.png">

**Comment by dimag0g** [comment]
@Conlin6241 So, as you can see, there is a definition of `eeprom_read_byte` there. Like I said, try to remove / stub `avr/eeprom.h`. You should be then getting "cannot include file" errors. If you don't, you're including the wrong file somehow.

If you do get the "cannot include file" errors, put `avr/eeprom.h` and generate a preprocessor listing your `Test.c`. This listing should contain a definition for `eeprom_read_byte` (essentially, a copy of `avr/eeprom.h`), before it is used in the definition of `EERef` structure.

**Comment by Conlin6241** [comment]
Essentially, I will have to include a copy of the avr/eeprom.h file in the Test.c file. Is this correct?

**Comment by dimag0g** [comment]
No, you're not supposed to copy .h files into .c files manually, although it will of course work. You should generate a preprocessor listing to understand what exactly happens in the `#include` lines.

Have you tried removing `avr/eeprom.h` to see if you really get a compilation error without it?

**Comment by Conlin6241** [comment]
Upon removing avr/eeprom.h, I get this error:

        avr/eeprom.c:3:20: fatal error: eeprom.h: No such file or directory

![image](https://user-images.githubusercontent.com/84931710/133299126-eb67679a-a062-4ae8-85af-c25c3f4dca13.png)

So in this case, generating a preprocessor listing would be my best option, correct?
