### ISSUE TITLE
Every letter in console displayed twice

### ISSUE THREAD

**Issue by alpensalamander** [dimag0g/nios_duino#3]
Hi,

I got the example program running with the MAX1000, but in the console the letters are all shown twice: 

NNoo  ddeevviicceess  ffoouunndd
11ss  iiss  883366mmss
AAnnaalloogg  ppiinn  11  vvaalluuee  ==  00
RReesseett  ccoouunntteerr  ==  11

**Comment by dimag0g** [comment]
This happens when you assign the same device to both STDOUT and STDERR. Output duplication is done to allow system with two output interfaces at once, like UART+JTAG_UART or UART+LCD.

Assigning STDERR to `none` should fix the double output problem.

**Comment by alpensalamander** [comment]
Thank you! Now it works
