### ISSUE TITLE
UART_0 works with Serial, but not with Serial0

### ISSUE THREAD

**Issue by leonbeier** [dimag0g/nios_duino#8]
This is my code
![image](https://user-images.githubusercontent.com/54705196/92752206-01884b80-f389-11ea-914c-2ce5b18eef15.png)
This is my uart_0 IP
![image](https://user-images.githubusercontent.com/54705196/92752402-31375380-f389-11ea-98f5-282ce8bc5100.png)

It works when I select uart_0 for stdout, but not directly with HardwareSerial

**Comment by leonbeier** [comment]
For me only 
IOWR_ALTERA_AVALON_UART_TXDATA(UART_0_BASE,'H');
ch = IORD_ALTERA_AVALON_UART_RXDATA(UART_0_BASE); 
works

**Comment by dimag0g** [comment]
This will require a lot of work for me to reproduce from scratch. Perhaps you could try debugging: step into `Serial0.println()` which in the end should call those Altera IO wrappers. Do the same for `Serial.println()` on a project with configured STDOUT, and hopefully the difference between the working and the non-working code will make it clear what is wrong.

**Comment by leonbeier** [comment]
What FPGA development board are you using?

**Comment by dimag0g** [comment]
@leonbeier  MAX1000. There's an FTDI chip on it converting UART to USB.

**Comment by leonbeier** [comment]
https://github.com/leonbeier/MAX10_NIOSDuino_Test
Does this help? I tested it on my MAX1000

**Comment by leonbeier** [comment]
I just used Serial with JTAG and Serial0 with UART

**Comment by dimag0g** [comment]
I think I found the bug. The `begin()` function was incorrectly opening the UART in mode 0 (which is `O_RDONLY`), instead of `O_RDWR`. Let me know it it works now.
