### ISSUE TITLE
Serial.ReadString() not working

### ISSUE THREAD

**Issue by hendrikmennen** [dimag0g/nios_duino#9]
This code will be stuck at readString() forever

```c++
#include <Arduino.h>

String incomingString = "";

void setup() {
    Serial.begin(9600); //Set Baudrate with "New Processor" test
}

void loop() {
    while(Serial.available()) 
    {
        incomingString = Serial.readString(); // read the incoming data as string
        
        Serial.println(incomingString);
    } 
}
```

**Comment by dimag0g** [comment]
Try running

    Serial.println("1");
    delay(1000);
    Serial.println("2");

Perhaps your time-related functions are way off, causing `readString()` to wait for data much longer than you expect. you need to calibrate  the `delay()` and `delayMicroseconds()` macros so that `delay(1000)` corresponds to one second.

**Comment by hendrikmennen** [comment]
I made sure the strings are escaped with `/r/n`. The timer seems to be working fine. Serial.read() is working as expected also. Just readString does not work and will hang forever once it get's executed

**Comment by dimag0g** [comment]
Hi, I think I found the issue, could you test the latest version?

**Comment by hendrikmennen** [comment]
Yes it works now thank you!
